DROP TABLE INVIA_A;
-- DROP TABLE PAGAMENTO;
-- DROP TABLE BONUS_ISCRIZIONE;
DROP TABLE CATEGORIA;
-- DROP TABLE LOCAZIONE;
DROP TABLE ANNUNCIO;
DROP TABLE SPEDIZIONE;
DROP TABLE ORDINE;
DROP TABLE UTENTE;
DROP TABLE RUOLI;
-- DROP TABLE MAGAZZINO;

