-- CREAZIONE ANNUNCIO
CREATE TABLE ANNUNCIO(
   ID_ANNUNCIO                INTEGER      PRIMARY KEY AUTO_INCREMENT,
   TITOLO_ANNUNCIO             VARCHAR(64)     NOT NULL,
   CATEGORIA_ANNUNCIO          VARCHAR(64)     NOT NULL,
   IMMAGINE                    LONGBLOB        NOT NULL,
   DISPONIBILE                 TINYINT(1)      NOT NULL DEFAULT 1,  
   PREZZO_PER_GIORNO_ANNUNCIO  INTEGER         NOT NULL,
   DESCRIZIONE_ANNUNCIO        VARCHAR(200)    NOT NULL,
   DATA_INIZIO_NOLEGGIO        DATE            NOT NULL,
   DATA_FINE_NOLEGGIO          DATE            NOT NULL, 
   DATA_INSERIMENTO_ANNUNCIO   DATE            NOT NULL,
   CITTA_ANNUNCIO              VARCHAR(64)     NOT NULL,
   PROVINCIA_ANNUNCIO          VARCHAR(64)     NOT NULL,
   VIA_ANNUNCIO                VARCHAR(120)    NOT NULL,
   CAP_ANNUNCIO                INTEGER         NOT NULL,
   ID_UTENTE_RF_ANNUNCIO       INTEGER         NOT NULL,
   CONSTRAINT FK_Proprietario_Annuncio FOREIGN KEY (ID_UTENTE_RF_ANNUNCIO) REFERENCES UTENTE (ID)
)