-- CREAZIONE CATEGORIA
CREATE TABLE CATEGORIA(
   ID_CATEGORIA                INTEGER       PRIMARY KEY,
   NOME_CATEGORIA              VARCHAR(50)   NOT NULL,
   ID_ANNUNCIO_RF_CATEGORIA    INTEGER       NOT NULL,
   CONSTRAINT FK_Id_Annuncio_Categoria FOREIGN KEY (ID_ANNUNCIO_RF_CATEGORIA) REFERENCES ANNUNCIO (ID_ANNUNCIO)
)