-- CREAZIONE RUOLI
CREATE TABLE RUOLI(
   ID                INTEGER      PRIMARY KEY, 
   NAME_ROLE         VARCHAR(64)  UNIQUE NOT NULL, 
   DEFAULT_ROLE      TINYINT      DEFAULT 1,
   PERMISSIONS       INTEGER      NOT NULL
);

INSERT INTO RUOLI(ID,NAME_ROLE,DEFAULT_ROLE,PERMISSIONS) VALUES (1,'User',1,7);
INSERT INTO RUOLI(ID,NAME_ROLE,DEFAULT_ROLE,PERMISSIONS) VALUES (2,'Administrator',0,31);

-- CREAZIONE UTENTE
CREATE TABLE UTENTE(  
   ID                          INTEGER        PRIMARY KEY AUTO_INCREMENT,  
   NOME_UTENTE                 VARCHAR(64)    NOT NULL,  
   COGNOME_UTENTE              VARCHAR(64)    NOT NULL,
   EMAIL                       VARCHAR(64)    NOT NULL UNIQUE, 
   USERNAME                    VARCHAR(64)    NOT NULL UNIQUE,
   PASSWORD_HASH               VARCHAR(128)   NOT NULL,
   CONFIRMED                   TINYINT(1)     NOT NULL, 
   ULTIMO_ACCESSO              DATE           NOT NULL,
   SESSO_UTENTE                CHAR(20)       NOT NULL, 
   DATA_DI_NASCITA_UTENTE      DATE           NOT NULL,          
   TELEFONO_UTENTE             CHAR(10)       NOT NULL, 
   CITTA_UTENTE                VARCHAR(64)    NOT NULL,
   PROVINCIA_UTENTE            VARCHAR(64)    NOT NULL,
   VIA_UTENTE                  VARCHAR(120)   NOT NULL,
   CAP_UTENTE                  INTEGER        NOT NULL,
   DATA_CREAZIONE_UTENTE       DATE           NOT NULL,
   ROLE_ID                     INTEGER        NOT NULL,
   CONSTRAINT FK_ROLE FOREIGN KEY(ROLE_ID) REFERENCES RUOLI(ID)       
);


-- CREAZIONE ORDINE
CREATE TABLE ORDINE(
   ID_ORDINE                      INTEGER  PRIMARY KEY AUTO_INCREMENT,
   TITOLO_ANNUNCIO                VARCHAR(64) NOT NULL,
   IMMAGINE                       LONGBLOB    NOT NULL,
   IMPORTO_PAGAMENTO              INTEGER  NOT NULL,
   DATA_INSERIMENTO_ORDINE        DATE     NOT NULL,
   ID_UTENTE_RF_ORDINE            INTEGER  NOT NULL,
   CONSTRAINT FK_Id_Annuncio FOREIGN KEY(ID_ANNUNCIO_RF_ORDINE) REFERENCES ANNUNCIO(ID)
);


-- CREAZIONE SPEDIZIONE
CREATE TABLE SPEDIZIONE(
   ID_SPEDIZIONE               INTEGER        PRIMARY KEY AUTO_INCREMENT,
   DATA_SPEDIZIONE             DATE           NOT NULL,
   SPESA_DI_SPEDIZIONE         INTEGER        NOT NULL DEFAULT 10,
   VIA_SPEDIZIONE              VARCHAR(120)   NOT NULL,
   CITTÀ_SPEDIZIONE            VARCHAR(64)    NOT NULL,
   PROVINCIA_SPEDIZIONE        VARCHAR(64)    NOT NULL,
   CAP_SPEDIZIONE              INTEGER        NOT NULL,
   ID_ORDINE_RF_SPEDIZIONE     INTEGER        NOT NULL,
   CONSTRAINT FK_Id_Ordine_Spedizione FOREIGN KEY (ID_ORDINE_RF_SPEDIZIONE) REFERENCES ORDINE (ID_ORDINE)
);

-- CREAZIONE ANNUNCIO
CREATE TABLE ANNUNCIO(
   ID_ANNUNCIO                INTEGER      PRIMARY KEY AUTO_INCREMENT,
   TITOLO_ANNUNCIO             VARCHAR(64)     NOT NULL,
   CATEGORIA_ANNUNCIO          VARCHAR(64)     NOT NULL,
   IMMAGINE                    LONGBLOB        NOT NULL,
   DISPONIBILE                 TINYINT(1)      NOT NULL DEFAULT 1,  
   PREZZO_PER_GIORNO_ANNUNCIO  INTEGER         NOT NULL,
   DESCRIZIONE_ANNUNCIO        VARCHAR(200)    NOT NULL,
   DATA_INIZIO_NOLEGGIO        DATE            NOT NULL,
   DATA_FINE_NOLEGGIO          DATE            NOT NULL, 
   DATA_INSERIMENTO_ANNUNCIO   DATE            NOT NULL,
   CITTA_ANNUNCIO              VARCHAR(64)     NOT NULL,
   PROVINCIA_ANNUNCIO          VARCHAR(64)     NOT NULL,
   VIA_ANNUNCIO                VARCHAR(120)    NOT NULL,
   CAP_ANNUNCIO                INTEGER         NOT NULL,
   ID_UTENTE_RF_ANNUNCIO       INTEGER         NOT NULL,
   CONSTRAINT FK_Proprietario_Annuncio FOREIGN KEY (ID_UTENTE_RF_ANNUNCIO) REFERENCES UTENTE (ID)
);

-- CREAZIONE CATEGORIA
CREATE TABLE CATEGORIA(
   ID_CATEGORIA                INTEGER       PRIMARY KEY AUTO_INCREMENT,
   NOME_CATEGORIA              VARCHAR(64)   NOT NULL,
   ID_ANNUNCIO_RF_CATEGORIA    INTEGER       NOT NULL,
   CONSTRAINT FK_Id_Annuncio_Categoria FOREIGN KEY (ID_ANNUNCIO_RF_CATEGORIA) REFERENCES ANNUNCIO (ID_ANNUNCIO)
);

-- CREAZIONE INVIA_A
CREATE TABLE INVIA_A(
   ID_UTENTE_DESTINATARIO_RF_INVIA_A  INTEGER NOT NULL,
   ID_SPEDIZIONE_RF_INVIA_A           INTEGER NOT NULL,
   CONSTRAINT PK_INVIA_A              PRIMARY KEY(ID_UTENTE_DESTINATARIO_RF_INVIA_A,ID_SPEDIZIONE_RF_INVIA_A), 
   CONSTRAINT FK_Id_utente_destinatario FOREIGN KEY(ID_UTENTE_DESTINATARIO_RF_INVIA_A) REFERENCES UTENTE(ID),  
   CONSTRAINT FK_Id_spedizione FOREIGN KEY(ID_SPEDIZIONE_RF_INVIA_A) REFERENCES SPEDIZIONE(ID_SPEDIZIONE)
);