-- CREAZIONE INVIA_A
CREATE TABLE INVIA_A(
   ID_UTENTE_DESTINATARIO_RF_INVIA_A  INTEGER NOT NULL,
   ID_SPEDIZIONE_RF_INVIA_A           INTEGER NOT NULL,
   CONSTRAINT PK_INVIA_A              PRIMARY KEY(ID_UTENTE_DESTINATARIO_RF_INVIA_A,ID_SPEDIZIONE_RF_INVIA_A), 
   CONSTRAINT FK_Id_utente_destinatario FOREIGN KEY(ID_UTENTE_DESTINATARIO_RF_INVIA_A) REFERENCES UTENTE(ID),  
   CONSTRAINT FK_Id_spedizione FOREIGN KEY(ID_SPEDIZIONE_RF_INVIA_A) REFERENCES SPEDIZIONE(ID_SPEDIZIONE)
)