-- CREAZIONE RUOLI
CREATE TABLE RUOLI(
   ID                INTEGER      PRIMARY KEY, 
   NAME_ROLE         VARCHAR(64)  UNIQUE NOT NULL, 
   DEFAULT_ROLE      TINYINT      DEFAULT 1,
   PERMISSIONS       INTEGER      NOT NULL
);