-- CREAZIONE SPEDIZIONE
CREATE TABLE SPEDIZIONE(
   ID_SPEDIZIONE               INTEGER        PRIMARY KEY,
   DATA_SPEDIZIONE             DATE           NOT NULL,
   SPESA_DI_SPEDIZIONE         INTEGER        NOT NULL  DEFAULT 10,
   VIA_SPEDIZIONE              VARCHAR(120)   NOT NULL,
   CITTÀ_SPEDIZIONE            VARCHAR(64)    NOT NULL,
   PROVINCIA_SPEDIZIONE        VARCHAR(64)    NOT NULL,
   CAP_SPEDIZIONE              INTEGER        NOT NULL,
   ID_ORDINE_RF_SPEDIZIONE     INTEGER        NOT NULL,
   CONSTRAINT FK_Id_Ordine_Spedizione FOREIGN KEY (ID_ORDINE_RF_SPEDIZIONE) REFERENCES ORDINE (ID_ORDINE)
)